# Generated by Django 5.0.2 on 2024-02-21 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mistakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ishturi_or_Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ish_id', models.IntegerField(default=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_id', models.PositiveIntegerField(unique=True)),
                ('mahsulot_nomi', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Xato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xato_id', models.IntegerField(blank=True, default=1, null=True, unique=True, verbose_name='xato id si')),
                ('problem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bulim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim_nomi', models.CharField(max_length=50)),
                ('bolim_id', models.PositiveIntegerField()),
                ('bolim_rahbari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], default='erkak', max_length=10)),
                ('ism', models.CharField(error_messages={'required': 'this field is required'}, max_length=50)),
                ('familiya', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('id_raqam', models.IntegerField(default=1, unique=True)),
                ('ish_turi', models.ManyToManyField(to='Mistakes.ishturi_or_bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Workinspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xato_soni', models.PositiveIntegerField(null=True)),
                ('yaroqli_product_soni', models.PositiveIntegerField(null=True)),
                ('ish_vaqti', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the article was published', verbose_name='vaqt/soat')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='vaqtni yangilash')),
                ('izoh', models.TextField(null=True)),
                ('mahsulot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mistakes.mahsulot')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mistakes.xato')),
                ('xodim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mistakes.xodim')),
            ],
        ),
    ]
